version: "3.7"
services:
  visualizer:
    image: 192.168.173.91:8082/repository/container/visualizer:latest
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.role == manager]
  nginx:
    image: 192.168.173.91:8082/repository/container/nginx:latest
    networks:
      - devops_net
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    deploy:
      placement:
        constraints: [node.hostname == vincent]
    depends_on:
      - gateway
  prometheus:
    image: 192.168.173.91:8082/repository/container/prometheus:latest
    networks:
      - devops_net
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
    deploy:
      placement:
        constraints: [node.hostname == vincent]
  sentinel-dashboard:
    hostname: sentinel
    image: 192.168.173.91:8082/repository/container/sentinel_dashboard:1.7.1
    networks:
      - devops_net
    ports:
      - "8858:8858"
    depends_on:
      - sentinel
  sentinel-token-server:
    hostname: sentinel-envoy-rls-token-server
    image: 192.168.173.91:8082/repository/container/sentinel-cluster-server:latest
    networks:
      - devops_net
    ports:
      - "8719:8719"
    deploy:
      placement:
        constraints: [node.role == manager]
  nacos:
    hostname: nacos
    image: 192.168.173.91:8082/repository/container/nacos-server:latest
    networks:
      - devops_net
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
    deploy:
      placement:
        constraints: [node.role == manager]
  server:
    image: 192.168.173.91:8082/repository/container/server:latest
    networks:
      - devops_net
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - nacos
      - sentinel-dashboard
  gateway:
    hostname: gateway
    image: 192.168.173.91:8082/repository/container/gateway:latest
    networks:
      - devops_net
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - nacos
      - sentinel-dashboard
  client:
    image: 192.168.173.91:8082/repository/container/client:latest
    networks:
      - devops_net
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 2
    depends_on:
      - nacos
      - sentinel-dashboard
      - sentinel-token-server
networks:
  devops_net:
    external: true
