version: "3.7"
services:
  nginx:
    image: 192.168.173.91:8082/repository/container/nginx:latest
    networks:
      - devops_net
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    deploy:
      placement:
        constraints: [node.role == manager]
  server:
    image: 192.168.173.91:8082/repository/container/server:latest
    networks:
      - devops_net
    deploy:
      mode: replicated
      replicas: 4
  client:
    hostname: client
    image: 192.168.173.91:8082/repository/container/client:latest
    ports:
      - "8845:8080"
    networks:
      - devops_net
    deploy:
      mode: replicated
      replicas: 4
  nacos:
    hostname: nacos
    image: 192.168.173.91:8082/repository/container/nacos-server:latest
    networks:
      - devops_net
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
    deploy:
      placement:
        constraints: [node.role == manager]
  visualizer:
    image: 192.168.173.91:8082/repository/container/visualizer:latest
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  devops_net:
    external: true
