version: "3.7"
services:
  visualizer:
    image: 192.168.173.91:8082/repository/container/visualizer:latest
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.role == manager]
  nginx:
    image: 192.168.173.91:8082/repository/container/nginx:latest
    networks:
      - devops_net
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    deploy:
      placement:
        constraints: [node.hostname == vincent]
  sentinel:
    hostname: sentinel
    image: 192.168.173.91:8082/repository/container/sentinel_dashboard:1.3.0
    networks:
      - devops_net
    ports:
      - "8858:8858"
  sentinel-cluster-server:
    hostname: sentinel-cluster-server
    image: 192.168.173.91:8082/repository/container/sentinel-cluster-server:latest
    networks:
      - devops_net
  nacos:
    hostname: nacos
    image: 192.168.173.91:8082/repository/container/nacos-server:latest
    networks:
      - devops_net
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
  server:
    image: 192.168.173.91:8082/repository/container/server:latest
    networks:
      - devops_net
    deploy:
      mode: replicated
      replicas: 3
  client:
    hostname: client
    image: 192.168.173.91:8082/repository/container/client:latest
    networks:
      - devops_net
    deploy:
      mode: replicated
      replicas: 2
networks:
  devops_net:
    external: true
