version: "3.7"
services:
  nginx:
    image: 192.168.173.91:8082/repository/container/nginx:latest
    networks:
      - devops_net
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    deploy:
      placement:
        constraints: [node.role == manager]
  redis:
    hostname: redis
    image: 192.168.173.91:8082/repository/container/redis:latest
    networks:
      - devops_net
    ports:
      - "7369:7369"
  sentinel:
    hostname: sentinel
    image: 192.168.173.91:8082/repository/container/sentinel_dashboard:1.3.0
    networks:
      - devops_net
    ports:
      - "8858:8858"
  nacos:
    hostname: nacos
    image: 192.168.173.91:8082/repository/container/nacos-server:latest
    networks:
      - devops_net
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
  visualizer:
    image: 192.168.173.91:8082/repository/container/visualizer:latest
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  devops_net:
    external: true
