version: "3.7"
#version: "2"
services:
  server:
#    hostname: devops_server
    image: 192.168.173.91:8082/repository/container/server:latest
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
  client:
#    hostname: devops_client
    image: 192.168.173.91:8082/repository/container/client:latest
    networks:
      - net
#    ports:
#      - "8083:8080"
    deploy:
      mode: replicated
      replicas: 1
  nacos:
    hostname: nacos
    image: 192.168.173.91:8082/repository/container/nacos-server:latest
    networks:
      - net
    environment:
      - MODE=standalone
#    ports:
#      - "8848:8848"
#      - "9555:9555"
  visualizer:
    image: 192.168.173.91:8082/repository/container/visualizer:latest
    networks:
      - net
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  net:
    driver: overlay
    ipam:
      config:
        - subnet: 10.0.9.0/24
#    external: true
