version: "3.7"
services:

  visualizer:
    image: dockersamples/visualizer
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.role == manager]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - devops_net

  sentinel:
    hostname: sentinel
    image: 192.168.173.91:8082/repository/container/sentinel_dashboard:1.3.0
    ports:
      - "8858:8858"
    networks:
      - devops_net

  nacos:
    hostname: nacos
    image: nacos/nacos-server:latest
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
    networks:
      - devops_net

  server:
    image: xbw1220/server:latest
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - devops_net

  client:
    hostname: client
    image: xbw1220/client:latest
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - devops_net

networks:
  net:

