name: devops Java CI

#on: [push]
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

      #        mvn -q -e -B -U clean install -pl devops-client/devops-client-api
    - name: Build
      run: |
        mvn -q -e -B -U clean install
        mvn -q -e -B -U clean package -Dmaven.test.skip=true -pl devops-server/devops-server-web,devops-client/devops-client-web

    - name: Upload Artifact client-web
      uses: actions/upload-artifact@v1
      with:
        name: clinet-web
        path: devops-client/devops-client-web/target/*.jar

    - name: Upload Artifact server-web
      uses: actions/upload-artifact@v1
      with:
        name: server-web
        path: devops-server/devops-server-web/target/*.jar
      

