name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
#       run: mvn -B package --file pom.xml
      run: mvn -q -e -B -U install -Dmaven.test.skip=true -pl devops-server/devops-server-web,devops-client/devops-client-web
           mvn -q -e -B -U package -Dmaven.test.skip=true -pl devops-server/devops-server-web,devops-client/devops-client-web
      

